# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GameLine' do
  # Comment the next line if you don't want to use dynamic frameworks
  # Add Parse pods and install
  use_frameworks!

  # Pods for GameLine
   pod 'Parse'
   pod 'AlamofireImage'
   pod 'MessageInputBar'

  target 'GameLineTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GameLineUITests' do
    inherit! :search_paths
    #Pods for testing
  end

end
